[package]
name = "chip8-rust"
version = "0.1.0"
authors = ["Daniel Coady <daniel.coady@outlook.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
